server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # React Router – skicka allt till index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy till User/Order Service
    location /api/auth/ {
        proxy_pass http://user-order-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/orders/ {
        proxy_pass http://user-order-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy till Product Service
    location /products {
        proxy_pass http://product-service:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    gzip on;
    gzip_types text/plain application/javascript text/css;
}